title: OpenShift AI Kubernetes API Documentation
description: Comprehensive guide for using Kubernetes API to create OpenShift AI resources and served models
baseurl: "/rhoai-api-docs"
url: "https://cfchase.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: just-the-docs

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
header_pages:
  - index.md
  - docs/getting-started.md
  - docs/kubernetes-api.md
  - docs/modelcar-serving.md
  - docs/examples.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true